/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ConundrumRouteImport } from './routes/conundrum'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminConundrumsRouteImport } from './routes/admin.conundrums'
import { Route as AdminBgmRouteImport } from './routes/admin.bgm'

const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConundrumRoute = ConundrumRouteImport.update({
  id: '/conundrum',
  path: '/conundrum',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConundrumsRoute = AdminConundrumsRouteImport.update({
  id: '/conundrums',
  path: '/conundrums',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBgmRoute = AdminBgmRouteImport.update({
  id: '/bgm',
  path: '/bgm',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/conundrum': typeof ConundrumRoute
  '/quotes': typeof QuotesRoute
  '/admin/bgm': typeof AdminBgmRoute
  '/admin/conundrums': typeof AdminConundrumsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conundrum': typeof ConundrumRoute
  '/quotes': typeof QuotesRoute
  '/admin/bgm': typeof AdminBgmRoute
  '/admin/conundrums': typeof AdminConundrumsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/conundrum': typeof ConundrumRoute
  '/quotes': typeof QuotesRoute
  '/admin/bgm': typeof AdminBgmRoute
  '/admin/conundrums': typeof AdminConundrumsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/conundrum'
    | '/quotes'
    | '/admin/bgm'
    | '/admin/conundrums'
    | '/admin/quotes'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conundrum'
    | '/quotes'
    | '/admin/bgm'
    | '/admin/conundrums'
    | '/admin/quotes'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/conundrum'
    | '/quotes'
    | '/admin/bgm'
    | '/admin/conundrums'
    | '/admin/quotes'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConundrumRoute: typeof ConundrumRoute
  QuotesRoute: typeof QuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conundrum': {
      id: '/conundrum'
      path: '/conundrum'
      fullPath: '/conundrum'
      preLoaderRoute: typeof ConundrumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conundrums': {
      id: '/admin/conundrums'
      path: '/conundrums'
      fullPath: '/admin/conundrums'
      preLoaderRoute: typeof AdminConundrumsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bgm': {
      id: '/admin/bgm'
      path: '/bgm'
      fullPath: '/admin/bgm'
      preLoaderRoute: typeof AdminBgmRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBgmRoute: typeof AdminBgmRoute
  AdminConundrumsRoute: typeof AdminConundrumsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBgmRoute: AdminBgmRoute,
  AdminConundrumsRoute: AdminConundrumsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConundrumRoute: ConundrumRoute,
  QuotesRoute: QuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
